export const REMOVE_PERSON = 'REMOVE_PERSON';
export const ADD_FETCHED_PEOPLE = 'ADD_FETCHED_PEOPLE';
export const ADD_FETCHED_STARSHIPS = 'ADD_FETCHED_STARSHIPS';
export const ADD_FETCHED_FILMS = 'ADD_FETCHED_FILMS';
export const ADD_FETCHED_SPECIES = 'ADD_FETCHED_SPECIES';
export const ADD_FETCHED_VEHICLES = 'ADD_FETCHED_VEHICLES';
export const ADD_FETCHED_PLANETS = 'ADD_FETCHED_PLANETS';